# Generated by Django 2.1 on 2018-12-04 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_signature'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Signature',
        ),
    ]
