# Generated by Django 2.1 on 2018-12-04 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_delete_signature'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature_image', models.ImageField(null=True, upload_to='', verbose_name='')),
                ('signature_owner', models.CharField(max_length=50)),
            ],
        ),
    ]
