# Generated by Django 2.1 on 2018-12-06 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signature',
            name='signature_image',
            field=models.TextField(null=True),
        ),
    ]
