# Generated by Django 2.1 on 2018-12-06 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20181206_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signature',
            name='signature_image',
            field=models.CharField(max_length=50000, null=True),
        ),
    ]
