# Generated by Django 2.1 on 2018-12-06 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20181206_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signature',
            name='signature_image',
            field=models.ImageField(null=True, upload_to='', verbose_name=''),
        ),
    ]
