# Generated by Django 2.1 on 2018-12-06 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20181206_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='display',
            field=models.BooleanField(null=True),
        ),
    ]
